##  No Hidden layers

In [2]:
import numpy as np

In [63]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [7]:
def sig(z):
    return 1/(1+np.exp(-z))

In [17]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [42]:
#no hidden layer
# weights = 2 * np.random.random((2,1)) - 1
# bais = 2 * np.random.random(1) - 1
# lr = 0.01
# weights,bais

(array([[ 0.19225879],
        [-0.68617919]]), array([-0.94748922]))

In [72]:
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
lr = 0.1
weights, bias

(array([[ 0.83508785],
        [-0.48865845]]), array([-0.34629789]))

In [78]:
#no hidden layer
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0,weights)+bias)


    first_term = output-Y
    input_for_the_last_layer = np.dot(output0,weights)+bais
    second_term = DerivativeSig(input_for_the_last_layer)
    first_two = first_term * second_term
    
    first_two.shape
    changes = np.array([[0.0],[0.0]])

    for i in range(2):
        for j in  range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]
    weights = weights-  lr*changes
    bais_change = 0.0
    for j in range(4):
        bais_change += first_two[j][0] *1
    bias = bias - lr*bais_change

output = sig(np.dot(X,weights)+bias)
weights,bias,output

(array([[6.55847355],
        [6.55847355]]), array([-10.68602841]), array([[2.28616145e-05],
        [1.58664489e-02],
        [1.58664489e-02],
        [9.19154826e-01]]))

In [79]:
#no hidden layer
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0,weights)+bias)


    first_term = output-Y
    input_for_the_last_layer = np.dot(output0,weights)+bais
    second_term = DerivativeSig(input_for_the_last_layer)
    first_two = first_term * second_term
    
    first_two.shape
    changes = np.dot(output0.T,first_two)

    weights = weights-  lr*changes
    bais_change = np.sum(first_two)
    bias = bias - lr*bais_change

output = sig(np.dot(X,weights)+bias)
weights,bias,output

(array([[6.50448825],
        [6.50448825]]), array([-10.79883995]), array([[2.04227644e-05],
        [1.34617243e-02],
        [1.34617243e-02],
        [9.01156090e-01]]))

## Hidden Layer Neural Network (XOR)

In [3]:
Xh = np.array([[0,0],[0,1],[1,0],[1,1]])
Yh = np.array([[0,1,1,0]]).T
Xh.shape,Yh.shape

((4, 2), (4, 1))

In [4]:
wh = 2*np.random.random((2,2))-1
bh = 2*np.random.random((1,2))-1
wo = 2*np.random.random((2,1))-1
bo = 2*np.random.random((1,1)) -1
lr = 0.1

In [20]:
#forward propagation
for iter in range(10000):
    output0 =Xh
    inputHidden = np.dot(output0,wh)+bh
    outputHidden = sig(inputHidden)
    inputforOutputLayer = np.dot(outputHidden,wo)+ bo 
    output = sig(inputforOutputLayer)
    output

    first_term_for_output_layer = output-Yh
    second_term_output_layer = derivativeSig(inputforOutputLayer)
    first_two_term_output_layer = first_term_for_output_layer*second_term_output_layer
    first_term_hidden_layer = np.dot(first_two_term_output_layer,wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer

    changes_output = np.dot(outputHidden.T,first_two_term_output_layer)
    changes_output_bias = np.sum(first_two_term_output_layer,axis=0,keepdims=True)

    changes_hidden = np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer,axis=0,keepdims=True)

    wo = wo-lr*changes_output
    bo = bo-lr*changes_output_bias

    wh = wh - lr*changes_hidden
    bh = bh - lr*changes_hidden_bias
output0 =Xh
inputHidden = np.dot(output0,wh)+bh
outputHidden = sig(inputHidden)
inputforOutputLayer = np.dot(outputHidden,wo)+ bo 
output = sig(inputforOutputLayer)
output,wh,bh,wo,bo

(array([[0.04218936],
        [0.95282516],
        [0.95996342],
        [0.03735394]]), array([[ 4.91616033,  5.62227738],
        [-5.14461895, -5.55010192]]), array([[-2.67450006,  2.85794844]]), array([[ 7.98928045],
        [-7.5259943 ]]), array([[3.47979419]]))